from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
HTTP = HTTPRemoteProvider()

configfile: "config/config.yaml"
metadata = "metadata"

rnaseq_files, = glob_wildcards("rawdata/rnaseq/{sample}.fastq.gz")
samples = list(set([sample.split("_")[0] for sample in rnaseq_files]))[0]
samples = ["586988"]

include: "rules/expression.smk"
include: "rules/downloadData.smk"




rule processTreatmentResponse:
    input:
        GRMetrics = "rawdata/TreatmentResponse_and_Metadata/gCSI_GRmetrics_v1.3.tsv",
        GRValues = "rawdata/TreatmentResponse_and_Metadata/gCSI_GRvalues_v1.3.tsv",
    output:
        TRPreprocessed = "procdata/TreatmentResponsePreprocessed.RDS",
    conda:
        "envs/r-base.yaml"
    script: 
        "scripts/processTreatmentResponse.R"

rule preprocessMetadata:
    input:
        GRValues = "rawdata/TreatmentResponse_and_Metadata/gCSI_GRvalues_v1.3.tsv",
    output:
        treatmentMetadata = "metadata/treatmentMetadata.tsv",
        sampleMetadata = "metadata/sampleMetadata.tsv",
    conda:
        "envs/r-base.yaml"
    script:
        "scripts/preprocessMetadata.R"

    
